import Head from "next/head";
import Router from "next/router";
import { useState } from "react";
import { toast } from "react-toastify";

export default function Home() {
  const [email, setEmail] = useState("pr16866@gmail.com");
  const emailAuth = () => {
    // toast.warn("Verifing email");
    if (!email) {
      toast.warn("Please enter the admin email");
      return;
    }
    if (email === "pr16866@gmail.com"){
    // if (email === "urbancarwash05@gmail.com"){
      Router.push("/booking?type=One_time_wash");
    }
    else {
      toast.warn("Admin email is not verified");
      return;
    }
  }
  return (
    <div className="flex justify-center items-center min-h-screen">
      <Head>
        <title>The urban car wash || dashbord</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container bg-[#FFC044] w-screen h-screen flex justify-center items-center">
        <div className="flex justify-center items-center md:mt-[150px] md:mb-[83px] mt-[132px] mb-[83px]">
          <div className="flex flex-col  w-[70vw] bg-[#141414] rounded-[10px] mx-auto py-[80px]">
            <div className="md:w-1/2 w-[90%] p-5 mx-auto mb-2">
              <div id="sign-in-button"></div>
              <label
                htmlFor="phone_number"
                className="block mb-1 font-semibold text-white text-semibold text-[15px]">
               Please enter Email 
              </label>
              <input
                type="email"
                name="email"
                placeholder="Enter email"
                className="w-full text-[14px] px-4 py-[10px] rounded outline-none"
                onChange={(event) => setEmail(event.target.value)}
              />
            </div>

            <div className="flex justify-center items-center p-5 md:w-1/2 w-[90%] mx-auto">
              <button
                className="w-full font-medium text-center py-4 rounded-[8px] bg-[#FFC044]"
                onClick={emailAuth}
              >
               Verify Email
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
